name: Deploy topics til prod

on:
  push:
    tags:
      - prod/*

jobs:
  deploy-krav-topic-to-prod:
    name: Deploy krav-topic to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: topics/prod/krav-topic.yaml

  deploy-soeknad-topic-to-prod:
    name: Deploy søknad-topic to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: topics/prod/soeknad-topic.yaml

  deploy-im-topic-to-prod:
    name: Deploy im-topic to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: topics/prod/inntektsmelding-topic.yaml